const COMMENT_MAX_DEPTH = 3;

const MIN_NAME_LENGTH = 1;
const MAX_NAME_LENGTH = 50;

const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 300;

const MIN_COMMENT_LENGTH = 1;
const MAX_COMMENT_LENGTH = 1000;

const MAX_POST_PER_PAGE = 20;

export {
  COMMENT_MAX_DEPTH,
  MAX_COMMENT_LENGTH,
  MAX_NAME_LENGTH,
  MAX_PASSWORD_LENGTH,
  MAX_POST_PER_PAGE,
  MIN_COMMENT_LENGTH,
  MIN_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
};
